### ISSUE TITLE
[feat] 학교 조회 시 스케쥴링 변경으로 인한 오류 관련 수정 

### ISSUE THREAD

**Issue by khyojun** [capstone-kw-jjiggle/gitbal-be#120]
## 🛠️ 작업 설명
>어떤 작업인지 간략하게 설명해주세요!

학교 이름들을 조회하였지만 스케쥴링으로 인한 업데이트로 인하여 학교 랭킹 업데이트가 진행되지 못한 부분에 있는 부분에 대한 수정을 진행한다.

## 🔍 Todo
> 개발할 기능에 대해 적어주세요!

- [x] 유저 score 업데이트에 따른 학교 랭킹 업데이트 관련 업데이트 작업 진행

## 📃 참고한 출처
> 어느 출처를 참고했는지 작성해주세요!
- 
-

**Comment by leesj000603** [comment]
close#120
