### ISSUE TITLE
[feat] data.sql insert문 작성

### ISSUE THREAD

**Issue by leesj000603** [capstone-kw-jjiggle/gitbal-be#30]
## 🛠️ 작업 설명
>어떤 작업인지 간략하게 설명해주세요!

약 400개의 대학교 이름과 10개 지역 이름을 school, region table에 insert하는 data.sql 작성

## 🔍 Todo
> 개발할 기능에 대해 적어주세요!

- [x] data.sql 작성

## 📃 참고한 출처
> 어느 출처를 참고했는지 작성해주세요!
- https://velog.io/@jupiter-j/%EC%8A%A4%ED%94%84%EB%A7%81%EB%B6%80%ED%8A%B8-%EC%8B%A4%ED%96%89-%EC%8B%9C-Database-sql-%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B2%A0%EC%9D%B4%EC%8A%A4-%EC%82%BD%EC%9E%85
-

**Comment by khyojun** [comment]
업무로 할당했었는데 실수로 #27 여기 커밋이랑 겹쳐버렸네요! pr 올려주시면 확인하고 먼저 올린 후에 확인하겠습니다..!
