### ISSUE TITLE
[docs] univcontroller의 tag 구현완료 표시로 변경

### ISSUE THREAD

**Issue by leesj000603** [capstone-kw-jjiggle/gitbal-be#38]
## 🛠️ 작업 설명
>어떤 작업인지 간략하게 설명해주세요!
univcontroller의 개발 및 검증이 완료되어 구현완료로 swagger 태그 변경했습니다.

## 🔍 Todo
> 개발할 기능에 대해 적어주세요!

## 📃 참고한 출처
> 어느 출처를 참고했는지 작성해주세요!
- 
-

**Comment by khyojun** [comment]
머지되었는데 close 키워드 깜빡하신거 같아 issue closes 시켰습니다.
