### ISSUE TITLE
[refactor] 반환 값 ResponseEntity로 감싸고 서비스 계층 커스텀 exception 적용

### ISSUE THREAD

**Issue by leesj000603** [capstone-kw-jjiggle/gitbal-be#82]
## 🛠️ 작업 설명
>어떤 작업인지 간략하게 설명해주세요!
반환 값 ResponseEntity로 감싸고 서비스 계층 커스텀 exception 적용

## 🔍 Todo
> 개발할 기능에 대해 적어주세요!

- [x] ResponseEntity 사용하지 않는 부분에 추가
- [x] Custom Exception 적용하기

## 📃 참고한 출처
> 어느 출처를 참고했는지 작성해주세요!
- 
-

**Comment by khyojun** [comment]
다음부터 close 키워드 사용해서 merge 될 때 이슈가 닫힐 수 있도록 해주세요!!!
