### ISSUE TITLE
[refactor] univcert 패키지 내부 관련하여 리팩토링 진행!

### ISSUE THREAD

**Issue by khyojun** [capstone-kw-jjiggle/gitbal-be#95]
## 🛠️ 작업 설명
>어떤 작업인지 간략하게 설명해주세요!

univcert 내부 패키지 관련 리팩토링을 진행해봅시다! -> 해당 패키지로 인해 변화하는 부가적인 간단한 작업같은건 동시에 진행해도 될 거 같습니다.

## 🔍 Todo
> 개발할 기능에 대해 적어주세요!

- [ ] todo
- [ ] todo

## 📃 참고한 출처
> 어느 출처를 참고했는지 작성해주세요!
- 
-

**Comment by leesj000603** [comment]
close
